version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.0
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.12

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: ./gradlew clean build
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests/test
          destination: test_result
      - store_artifacts:
          path: build/reports/jacoco
          destination: test_coverage
      - sonarcloud/scan


  test:
    docker:
      - image: cimg/openjdk:11.0.12
    steps:
      - checkout
      - run: ./gradlew test


workflows:
  build_and_test:
    jobs:
      - build:
          context: sonarcloud
      - test:
          requires:
            - build